api_version: "v1"
server:
  host: "0.0.0.0"
  port: 3000
  backend_notify_url: ""
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "disn"
  require_ssl: false
security:
  jwt_secret: "please-change-me"
passbase:
  secret_api_key: ""
did:
  didkit_path: "/Users/chris/dev/ott/repo/disn_src/play"
  api_key: "TYDF02847YU89583$JFLS989012"
  vc_issuer_port_start: 5000
  predefined_issuers: "ott,disn"
chain:
  controller_private_key: ""
  contract_abi_path: "chain/contract"
  contracts:
    -
      name: "identity"
      address: "0x76a7e650979fBeDf65dd69324673E6EB8CFe1C02"
    -
      name: "revoked_cert"
      address: "0x29Ded3d061d6845a5E169fcc5Ef526Ae826Ce65d"
  provider: ""
