api_version: "v1"
server:
  host: "0.0.0.0"
  port: 3000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "disn"
  require_ssl: false
security:
  jwt_secret: "please-change-me"
