api_version: "v1"
server:
  host: "0.0.0.0"
  port: 3000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "disn"
  require_ssl: false
security:
  jwt_secret: "please-change-me"
did:
  didkit_path: "/Users/chris/dev/ott/repo/disn_src/play"
  api_key: "FYUX02847GH34583$JFLS928734"
  vc_issuer_port_start: 5000
  predefined_issuers: "ott,disn"

